# https://taskfile.dev
version: "3"

tasks:
  install-doxygen:
    status:
      - which doxygen
    cmds:
      - sudo apt install -y doxygen

  docs:
    cmds:
      - task: install-doxygen
      - doxygen Doxyfile

  release:
    desc: publish release
    cmds:
      - test {{.CLI_ARGS}}
      - git tag {{.CLI_ARGS}}
      - git push
      - git push --tags
      - gh release create --generate-notes {{.CLI_ARGS}}
