version: "3"

vars:
  OUTPUT: "main.wasm"

env:
  WASI_SDK_PATH: /opt/wasi-sdk

tasks:
  default:
    - rm -f "{{.OUTPUT}}"
    - >
      "${WASI_SDK_PATH}/bin/clang++"
      --sysroot="${WASI_SDK_PATH}/share/wasi-sysroot"
      -o "{{.OUTPUT}}"
      -Wl,-zstack-size=14752,--no-entry
      -mexec-model=reactor
      -Wl,--initial-memory=65536,--max-memory=65536,--stack-first
      -Wl,--strip-all,--gc-sections,--lto-O3
      -Oz
      main.cpp
    - firefly_cli build
    - firefly_cli export
